version: "3.8"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./node-app:/app:ro
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  node_modules: